import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { primaryFont } from "@/styles/fonts";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

  {
    // const themeColors = {
    //   background: "#666",
   
    // };

    // :root {
    //   --background: ${themeColors.background};
     
    // }
    const customVariables = `
  `;


  return (
    <html lang="en">
      <head >
        {customVariables && <style dangerouslySetInnerHTML={{ __html: customVariables }} />}
      
      </head>
      <body
        className={`${primaryFont.className} ${geistMono.variable} antialiased bg-background dark:bg-dark-background transition-colors `}
      >
          {children}
      </body>
    </html>
  );
}
